# Request 
int64 marker_id      # Mandatory
float32 min_distance # Mandatory
float32 linear_vel   # Optional: Default is 0.5 m/s
float32 angular_vel  # Optional: Default is 0.5 rad/s
---
# Response
string message
bool success
---
# Feedback
float32 distance_to_marker
float32 curr_linear_vel
float32 curr_angular_vel