# Request
int64 marker_id # Mandatory
float32 angular_vel # Mandatory
int64 direction # Optional
                #  1 for counter-clockwise (Default)
                # -1 for clockwise
---
# Response
string message
bool success
---
# Feedback
float32 elapsed_time 
float32 curr_angular_vel