#Request
float32 angular_vel # Optional
int64 direction # Optional
                #  1 for counter-clockwise (Default)
                # -1 for clockwise
---
# Response
string message
bool success
---
# Feedback
float32 curr_angular_vel