# ROS2 Parameters for Ranger Server Node
# Author: Ziad Ammar
# Date: 12-7-2025
# Description: Configuration parameters for ranger_server action servers

ranger_server:
  ros__parameters:
    # Action Server Parameters
    follow_action:
      # Default velocity parameters
      default_linear_vel: 0.5    # m/s - Default linear velocity for follow action
      default_angular_vel: 0.15   # rad/s - Default angular velocity for follow action
      # Maximum velocity limits (safety parameters)
      max_linear_vel: 0.75         # m/s - Maximum allowed linear velocity
      max_angular_vel: 0.3        # rad/s - Maximum allowed angular velocity
      # Control parameters
      marker_timeout: 2.0         # s - Timeout for marker detection loss 
      # Smoothing parameters
      angular_gain: 1.0          # Proportional gain for angular control
      # Trapezoidal velocity profile parameters
      max_acceleration: 0.25       # m/s^2 - Maximum acceleration
      max_deceleration: 0.25       # m/s^2 - Maximum deceleration
      min_linear_vel_threshold: 0.05
      min_angular_vel_threshold: 0.0 
      deceleration_step_size: 0.02  # m/s - Step size for deceleration
      deceleration_distance_threshold: 1.0  # m - Distance threshold for deceleration to use min_deceleration_velocity
      min_deceleration_velocity: 0.1 # m/s^2 - Minimum deceleration at deceleration distance threshold
      # Alignment parameters
      alignment_tolerance: 0.01     # rad - Tolerance for alignment [Dead-Zone] (0.57 degrees)
    
    search_action:
      # Default velocity parameters
      default_angular_vel: 0.2    # rad/s - Default angular velocity for search action
      default_direction: 1        # 1 for counter-clockwise, -1 for clockwise
      # Maximum velocity limits (safety parameters)
      max_angular_vel: 0.3        # rad/s - Maximum allowed angular velocity for search
      # Timeout parameters
      search_timeout: 30.0        # s - Maximum time to search for marker
      # Alignment parameters
      alignment_tolerance: 0.01    # rad - Tolerance for alignment phase (0.57 degrees)

    strafe_action:
      # Default velocity
      default_vel: 0.4             # m/s - Default velocity for strafe action
      default_direction: 1          # 1 for left strafe, -1 for right strafe (TODO: CHECK DIRECTIONS)
      # Maximum velocity limits (safety parameters)
      max_vel: 0.5                 # m/s - Maximum allowed velocity
      # Timeout parameters
      strafe_timeout: 30.0
      # Acceleration/Deceleration parameters
      accel: 0.3                  # m/s^2 - Maximum acceleration for strafe action
      decel: 0.75                  # m/s^2 - Maximum deceleration for strafe action
      min_vel: 0.05                 # m/s - Minimum velocity during final approach
      # Alignment parameters
      alignment_tolerance: 0.05    # m - Tolerance for lateral alignment
      min_offset_for_decel: 0.3    # m - Minimum lateral offset to start deceleration

    # Topic and frame parameters
    topics:
      aruco_markers: "/aruco_markers"  # ArUco markers topic
      cmd_vel: "/cmd_vel"              # Velocity command topic
      
    # Control loop parameters
    control:
      loop_rate: 100.0             # Hz - Control loop frequency 
      feedback_rate: 10.0          # Hz - Feedback publishing frequency [NOTE: MAX 10 HZ to Avoid feedback message flooding]
      
    # Logging parameters
    logging:
      debug_enabled: false        # Enable debug logging
      throttle_duration: 2000     # ms - Duration for throttled warnings
